package com.reminder.model;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import java.util.Date;

@Entity
public class Reminder {
    @Id //primary key
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Integer id; // to be autogenerated field
    @NotNull
    private String name;
    private String description;
//    private Date dueDate; // should be received in the form yyyy-MM-dd ex. 2021-02-27
    @Column(name = "due_date")
    @NotNull
    private Long dueDate;
    @Enumerated (EnumType.STRING)
    @NotNull
    private ReminderStatus status;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Long getDueDate() {
        return dueDate;
    }

    public void setDueDate(Long dueDate) {
        this.dueDate = dueDate;
    }

    public ReminderStatus getStatus() {
        return status;
    }

    public void setStatus(ReminderStatus status) {
        this.status = status;
    }

    @Override
    public String toString() {
        return "Reminder{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", description='" + description + '\'' +
                ", dueDate=" + dueDate +
                ", status=" + status +
                '}';
    }
}
