package com.reminder.model;

import javax.persistence.*;
import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;
import java.util.Date;

@Entity
public class Reminder {
    @Id //primary key
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Integer id; // to be autogenerated field

    @NotNull
    @Column(name = "task_name")
    private String taskName;

    private String description;

//    private Date dueDate; // should be received in the form yyyy-MM-dd ex. 2021-02-27
    @Column(name = "due_date")
    @NotNull
    private Long dueDate;

    @Enumerated (EnumType.STRING)
    @NotNull
    private ReminderStatus status;

    @NotBlank //compulsory, not blank and also not null
    private String user;

    @NotBlank
    private String email;

    public Integer getId() {
        return id;
    }

    public String getTaskName() {
        return taskName;
    }

    public void setTaskName(String taskName) {
        this.taskName = taskName;
    }

    public String getUser() {
        return user;
    }

    public void setUser(String user) {
        this.user = user;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Long getDueDate() {
        return dueDate;
    }

    public void setDueDate(Long dueDate) {
        this.dueDate = dueDate;
    }

    public ReminderStatus getStatus() {
        return status;
    }

    public void setStatus(ReminderStatus status) {
        this.status = status;
    }

    @Override
    public String toString() {
        return "Reminder{" +
                "id=" + id +
                ", taskName='" + taskName + '\'' +
                ", description='" + description + '\'' +
                ", dueDate=" + dueDate +
                ", status=" + status +
                ", user='" + user + '\'' +
                ", email='" + email + '\'' +
                '}';
    }
}
